pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        app_version = 'version1'
    }
    stages{
        stage("Testing"){
            steps{
                script{
                        sh "bash Jenkins/test.sh"
                    }
                }
            }
        }
        stage("Build & Push"){
            steps{
                script{
                        sh "bash Jenkins/build_push.sh"
                    }
                }
            }
        stage("Config Management (ansible)"){
            steps{
                sh "bash Jenkins/config_ansible.sh"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash Jenkins/deploy.sh"
            }
        }
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable: false
        }
    }
}
        
