pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        app_version = 'version1'
    }
    stages{
        stage("Testing"){
            steps{
                        sh "bash Codes/Jenkins/test.sh"
                }
            }
        stage("Build & Push"){
            steps{
                        sh "bash Codes/Jenkins/build_push.sh"
                }
        }
        stage("Config Management (ansible)"){
            steps{
                        sh "bash Codes/Jenkins/config_ansible.sh"
                }
        }
        stage("Deploy"){
            steps{
			sh "bash Codes/Jenkins/deploy.sh"
                	}
        	}
	}
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable: false
        }
    }
} 
        
