---
- name: setup nginx
  hosts: nginx
  become: true
  roles:
    - nginx
- name: initialize docker swarm
  hosts: managers
  become: true
  roles:
    - docker
    - docker-swarm-init
- name: add worker to swarm
  hosts: workers
  become: true
  roles:
    - docker
    - docker-swarm-workers
